name: PR Comment Responder

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  respond:
    if: ${{ github.event.issue.pull_request != null && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Say hello world
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: "hello world",
            });

