name: Deploy Staging
on:
  workflow_dispatch:
  pull_request:
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: branch
        run: echo $BRANCH
        env:
          BRANCH: ${{ github.head_ref }} || ${{ github.ref }}
