name: Deploy

on: 
  workflow_dispatch:
    inputs:
      site:
        description: 'Production or staging'
        required: true
        type: choice
        options:
          - staging
          - production
  workflow_run:
    workflows: [Verify]
    types: [completed]
    branches: [master]

run-name: Deploy ${{ github.ref_name }} to ${{ inputs.site || 'production' }} by @${{ github.actor }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # If it's a workflow dispatch event, run it no matter what
    # Else, make sure the "verify" workflow succeeded, and that the commit message doesn't end with the string "[skip deploy]"
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        run: echo "${{ toJSON(github) }}"
