name: Deploy Staging
on:
  workflow_dispatch:
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "foo" > foo.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: foo.txt
          path: foo.txt
