name: Deploy

on: 
  workflow_dispatch:
    inputs:
      site:
        description: 'Production or staging'
        required: true
        type: choice
        options:
          - staging
          - production
  workflow_run:
    workflows: [Verify]
    types:
      - completed

run-name: Deploy ${{ github.ref_name }} to ${{ inputs.site || 'production' }} by @${{ github.actor }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deployed"
