name: Verify
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
    paths:
      - test-file.txt

jobs:
  add_comment:
    name: Add PR Comment
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        base-branch-regex: master
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        body-template: |
          ### Changes to Database Schema

          * [ ] It looks like these changes affect the database schema. have you issued a PR for the [`whatever`](https://github.com) repository that includes the updated schema? If not, please run `mix ecto.dump`, commit the changes to `structure.sql`, and create a new PR.

        body-update-action: suffix
