name: Verify

on: 
  workflow_dispatch:
    inputs:
      site:
        description: 'Production or staging'
        required: true
        type: choice
        options:
          - staging
          - production

run-name: Deploy to ${{ inputs.site }} by @${{ github.actor }}

jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "foo"
