name: Verify
on:
  pull_request:
    branches:
      - master
    types:
      - opened
    paths:
      - test-file.txt

jobs:
  add_comment:
    name: Add PR Comment
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            **Edit:** Some additional info
