name: Verify
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
    paths:
      - test-file.txt

jobs:
  add_comment:
    name: Add PR Comment
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        base-branch-regex: master
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token: abc
        body-template: |
          this should be appended
        body-update-action: suffix
